image:
  repository: clitest
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: LoadBalancer
  port: 22

# Additional volumes on the output Deployment definition.
volumes: 
  - name: ssh-volume
    configMap:
      name: ssh-config


# Additional volumeMounts on the output Deployment definition.
volumeMounts: 
  - name: ssh-volume
    subPath: sshd_config
    mountPath: /etc/ssh/sshd_config
  - name: ssh-volume
    subPath: authorized_keys
    mountPath: /root/.ssh/authorized_keys
  - name: ssh-volume
    subPath: authorized_keys
    mountPath: /home/workshop/.ssh/authorized_keys



# Add the corresponding public key here to be added to pod's authorized_keys
authorized_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiagnjg5Mr5hJoiQfk+jE20Q+/P/M1MV+uCa8P4Jmyj1XJtM/uJKoQuCX9pv7k5v9NMuUInaBM9h5+ouug9YZC5Xpl4X18wWrY17iwftUAAHrj1BLcbpX2jlfGSmF61efkZIBjUdrtJdFMEH7caImfLQ280lb0AmWxCrE5f3DHly9x03vdsnd7J95sdZ8T5SblC0Lj7XMEkygc+rGs3XVuJ9GRDBDw3HegRtAAJZCSFDktwPFxEWVVxIy0zPDd8wI8e8bJsJQ1wlLg3lTyJP+vPuaZi0IbNlVNyGCakHV07j58u8bEavvN+U824pEPDzat+Xz0+X2ACgbf4Kz6mPLuBrbrp2zswpD/TIBDB2rv1fKn6nozSGvnLOwKz9A1s1622Fi7ek7Bl8cL8B1aXTmzLWd2lVF46irCD7WjqVKWcsm4feeQgRWsWdxHUP1MXfDXcukxPv4M+ndY397kgE8U8baMJ54JUkX9PZ74Hr4f5O+mY+WAx9mxjSGkufCXVNM= ooijingkai10"