apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config-{{ .Release.Name }}
data:
  sshd_config: |
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    UsePAM no
    PermitUserRC yes
  ## Make this customizable
  authorized_keys: |
    {{.Values.authorized_keys}}

